"""stock reservations and payment orders

Revision ID: 01958a5469c7
Revises: 47977210c412
Create Date: 2026-09-19 01:56:28.856469

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "01958a5469c7"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "47977210c412"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_reservations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="ACTIVE", nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'CONSUMED', 'RELEASED', 'EXPIRED')",
            name="ck_stock_reservations_status",
        ),
        sa.CheckConstraint("quantity > 0", name="ck_stock_reservations_quantity_positive"),
        sa.ForeignKeyConstraint(
            ["business_id", "product_id"],
            ["inventory.business_id", "inventory.product_id"],
            name="fk_stock_reservations_business_product",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name="fk_stock_reservations_order", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "business_id", "order_id", "product_id", name="uq_stock_reservations_order_product"
        ),
    )
    op.create_index(
        "ix_stock_reservations_active_product",
        "stock_reservations",
        ["business_id", "product_id", "status", "expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_stock_reservations_business_order",
        "stock_reservations",
        ["business_id", "order_id"],
        unique=False,
    )
    op.add_column("invoices", sa.Column("order_id", sa.Uuid(), nullable=True))
    op.alter_column("invoices", "run_id", existing_type=sa.VARCHAR(length=160), nullable=True)
    op.alter_column("invoices", "quote_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("invoices", "quote_version", existing_type=sa.INTEGER(), nullable=True)
    op.create_unique_constraint(
        "uq_invoices_business_order", "invoices", ["business_id", "order_id"]
    )
    op.drop_constraint(
        op.f("fk_invoices_business_payment_quote_run"), "invoices", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_invoices_order", "invoices", "orders", ["order_id"], ["id"], ondelete="RESTRICT"
    )
    op.create_foreign_key(
        "fk_invoices_business_payment",
        "invoices",
        "payments",
        ["business_id", "payment_id"],
        ["business_id", "id"],
        ondelete="RESTRICT",
    )
    op.add_column("payments", sa.Column("order_id", sa.Uuid(), nullable=True))
    op.alter_column("payments", "run_id", existing_type=sa.VARCHAR(length=160), nullable=True)
    op.alter_column("payments", "quote_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("payments", "quote_version", existing_type=sa.INTEGER(), nullable=True)
    op.create_index(
        "ix_payments_business_order", "payments", ["business_id", "order_id"], unique=False
    )
    op.create_unique_constraint(
        "uq_payments_business_id_order", "payments", ["business_id", "id", "order_id"]
    )
    op.create_index(
        "uq_payments_one_active_or_paid_per_order",
        "payments",
        ["business_id", "order_id"],
        unique=True,
        postgresql_where=sa.text(
            "status IN ('CREATED', 'PENDING', 'PAID') AND order_id IS NOT NULL"
        ),
    )
    op.create_foreign_key(
        "fk_payments_order", "payments", "orders", ["order_id"], ["id"], ondelete="RESTRICT"
    )

    # Update Check Constraints for invoices
    op.drop_constraint("ck_invoices_run_nonempty", "invoices", type_="check")
    op.drop_constraint("ck_invoices_quote_version_positive", "invoices", type_="check")
    op.create_check_constraint(
        "ck_invoices_run_nonempty", "invoices", "length(trim(run_id)) > 0 OR run_id IS NULL"
    )
    op.create_check_constraint(
        "ck_invoices_quote_version_positive",
        "invoices",
        "quote_version > 0 OR quote_version IS NULL",
    )
    op.create_check_constraint(
        "ck_invoices_quote_or_order",
        "invoices",
        "(quote_id IS NOT NULL AND order_id IS NULL) OR (quote_id IS NULL AND order_id IS NOT NULL)",
    )

    # Update Check Constraints for payments
    op.drop_constraint("ck_payments_run_nonempty", "payments", type_="check")
    op.drop_constraint("ck_payments_quote_version_positive", "payments", type_="check")
    op.create_check_constraint(
        "ck_payments_run_nonempty", "payments", "length(trim(run_id)) > 0 OR run_id IS NULL"
    )
    op.create_check_constraint(
        "ck_payments_quote_version_positive",
        "payments",
        "quote_version > 0 OR quote_version IS NULL",
    )
    op.create_check_constraint(
        "ck_payments_quote_or_order",
        "payments",
        "(quote_id IS NOT NULL AND order_id IS NULL) OR (quote_id IS NULL AND order_id IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert check constraints before dropping order_id; PostgreSQL otherwise
    # removes the quote-or-order constraints implicitly with the column.
    op.drop_constraint("ck_invoices_quote_or_order", "invoices", type_="check")
    op.drop_constraint("ck_invoices_quote_version_positive", "invoices", type_="check")
    op.drop_constraint("ck_invoices_run_nonempty", "invoices", type_="check")
    op.create_check_constraint(
        "ck_invoices_quote_version_positive", "invoices", "quote_version > 0"
    )
    op.create_check_constraint("ck_invoices_run_nonempty", "invoices", "length(trim(run_id)) > 0")
    op.drop_constraint("ck_payments_quote_or_order", "payments", type_="check")
    op.drop_constraint("ck_payments_quote_version_positive", "payments", type_="check")
    op.drop_constraint("ck_payments_run_nonempty", "payments", type_="check")
    op.create_check_constraint(
        "ck_payments_quote_version_positive", "payments", "quote_version > 0"
    )
    op.create_check_constraint("ck_payments_run_nonempty", "payments", "length(trim(run_id)) > 0")
    op.drop_constraint("fk_payments_order", "payments", type_="foreignkey")
    op.drop_index(
        "uq_payments_one_active_or_paid_per_order",
        table_name="payments",
        postgresql_where=sa.text(
            "status IN ('CREATED', 'PENDING', 'PAID') AND order_id IS NOT NULL"
        ),
    )
    op.drop_constraint("uq_payments_business_id_order", "payments", type_="unique")
    op.drop_index("ix_payments_business_order", table_name="payments")
    op.alter_column("payments", "quote_version", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("payments", "quote_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("payments", "run_id", existing_type=sa.VARCHAR(length=160), nullable=False)
    op.drop_column("payments", "order_id")
    op.drop_constraint("fk_invoices_business_payment", "invoices", type_="foreignkey")
    op.drop_constraint("fk_invoices_order", "invoices", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_invoices_business_payment_quote_run"),
        "invoices",
        "payments",
        ["business_id", "payment_id", "quote_id", "run_id"],
        ["business_id", "id", "quote_id", "run_id"],
        ondelete="RESTRICT",
    )
    op.drop_constraint("uq_invoices_business_order", "invoices", type_="unique")
    op.alter_column("invoices", "quote_version", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("invoices", "quote_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("invoices", "run_id", existing_type=sa.VARCHAR(length=160), nullable=False)
    op.drop_column("invoices", "order_id")
    op.drop_index("ix_stock_reservations_business_order", table_name="stock_reservations")
    op.drop_index("ix_stock_reservations_active_product", table_name="stock_reservations")
    op.drop_table("stock_reservations")

    # ### end Alembic commands ###
