"""Add variant support to cart and order items

Revision ID: 3a4d86b03139
Revises: c82aaa6fcf01
Create Date: 2026-09-20 03:15:24.412519

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3a4d86b03139"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "c82aaa6fcf01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cart_items", sa.Column("variant_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        "fk_cart_items_variant",
        "cart_items",
        "product_variants",
        ["variant_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.add_column("order_items", sa.Column("variant_id", sa.Uuid(), nullable=True))
    op.add_column("order_items", sa.Column("size_snapshot", sa.String(length=255), nullable=True))
    op.add_column("order_items", sa.Column("color_snapshot", sa.String(length=255), nullable=True))
    op.create_foreign_key(
        "fk_order_items_variant",
        "order_items",
        "product_variants",
        ["variant_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("fk_order_items_variant", "order_items", type_="foreignkey")
    op.drop_column("order_items", "color_snapshot")
    op.drop_column("order_items", "size_snapshot")
    op.drop_column("order_items", "variant_id")
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("fk_cart_items_variant", "cart_items", type_="foreignkey")
    op.drop_column("cart_items", "variant_id")
    # ### end Alembic commands ###
